# Generated by Django 3.1.4 on 2021-03-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvitationEmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/logos')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('header', models.CharField(blank=True, max_length=100, null=True)),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('sms_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
