# Generated by Django 3.1.4 on 2021-03-03 15:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLink',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_full_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('data_partner_id', models.CharField(blank=True, max_length=50, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=9, null=True)),
                ('account_number', models.CharField(blank=True, max_length=12, null=True)),
                ('allocation_type', models.CharField(blank=True, choices=[('percent', 'Percent'), ('amount', 'Amount')], max_length=7, null=True)),
                ('allocation_value', models.IntegerField(blank=True, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('checking', 'Checking'), ('savings', 'Savings')], max_length=8, null=True)),
                ('argyle_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('argyle_token', models.CharField(blank=True, max_length=400, null=True)),
                ('argyle_account_id', models.UUIDField(blank=True, null=True)),
                ('encrypted_config', models.CharField(blank=True, max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedPayAllocation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.IntegerField(choices=[(1, 'Added'), (2, 'Updated'), (3, 'Removed')], default=1)),
                ('user_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_pay_allocations', to='link_generator.userlink')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedArgyleAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'Added'), (2, 'Connected'), (3, 'Failed'), (4, 'Removed')], default=1)),
                ('user_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to='link_generator.userlink')),
            ],
        ),
    ]
